module.exports = {
  UNAUTHORIZED: 'WB001',
  WORKSPACE_NOT_FOUND: 'WB002',
  PERMISSION_DENIED: 'WB003',
  PROJECT_ALREADY_EXISTS: 'WB004',
  MEMBER_ALREADY_EXISTS: 'WB005',
  VALIDATION_ERROR: 'WB006',
  INTERNAL_SERVER_ERROR: 'WB007',
  NOT_FOUND: 'WB008',
};
